config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do 
    resources :reviews, only: [:new, :create]
  end
  
  resources :categories 
  resources :users, only: [ :new, :create, :show ]
  
  get    'login', to: 'sessions#new'
  post   'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  root to: 'restaurants#index'
end

app/models/category.rb
class Category < ActiveRecord::Base
  include Sluggable
  has_many :restaurants
  validates :name, :slug, presence: true, uniqueness: true
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
  include Sluggable
  has_attached_file :image, styles: { large: "600x600>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  belongs_to :category
  has_many :reviews
  validates_uniqueness_of :name, :description
  validates_presence_of :name, :description, :category_id
  validates :slug, presence: true, uniqueness: true
end

app/models/review.rb
class Review < ActiveRecord::Base 
  belongs_to :restaurant
  belongs_to :user 
  validates_presence_of :rating, :content, :restaurant_id, :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :reviews, -> { order('created_at DESC')}
  validates_presence_of :username, :password
  validates_uniqueness_of :username 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  
  helper_method :current_user, :logged_in?, :review_exists_already?
  
  def current_user 
    @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  end 
  
  def logged_in?
    !!current_user
  end
  
  def review_exists_already?(restaurant, user)
    restaurant.reviews.reload.any? {|review| review[:user_id] == user.id }
  end
  
  def require_login
    if !logged_in?
      flash[:danger] = "Please sign in first"
      redirect_to login_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by(slug: params[:id])
  end
  
  def new
    @category = Category.new
  end

  def create
    @category = Category.create(category_params)

    if @category.save
      flash[:success] = "Your category was created successfully."
      redirect_to categories_path
    else
      render :new
    end
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :require_login, only: [:new, :create, :edit]
  before_action :setup_restaurant, only: [:show, :edit, :update]

  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:success] = "Your restaurant has been created!"
      redirect_to restaurants_path
    else
      render :new
    end
  end

  def show
    @review = @restaurant.reviews.build
  end

  def edit
  end

  def update
    @restaurant.update(restaurant_params)

    if @restaurant.save
      redirect_to restaurants_path
    else
      render :edit
    end
  end

  private

  def setup_restaurant
    @restaurant = Restaurant.find_by(slug: params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :description, :category_id, :image_url, :image)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @review = Review.new
  end
  
  def create
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = @restaurant.reviews.build(review_params) 
    @review.user_id = current_user.id
    
    if review_exists_already?(@restaurant, current_user)
      flash[:danger] = "You can only write one review"
      render 'restaurants/show'
    elsif @review.save
      flash[:success] = "Your review has been saved."
      redirect_to restaurant_path(@restaurant)
    else 
      render 'restaurants/show'
    end
  end
  
  private 
  
  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController 
  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id 
      flash[:success] = "Login successful!"
      redirect_to restaurants_path
    else 
      flash[:danger] = "Incorrect Username or Password!"
      render :new 
    end
  end
  
  def destroy
    session[:user_id] = nil 
    redirect_to restaurants_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new 
    @user = User.new 
  end
  
  def create 
    @user = User.new(user_params)
    if @user.save 
      flash[:success] = "User created successfully"
      session[:user_id] = @user.id 
      redirect_to restaurants_path
    else 
      render :new
    end
  end 
  
  def show 
    @user = User.find(params[:id])
  end
  
  private 
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def clean_date_format(object)
    object.created_at.strftime('Reviewed on %a %b %e at I:%M%p')
  end
  
  def rating_options
    (1..5).map { |num| ["#{pluralize( num, "Star")}", num] }
  end
end

app/views/categories/index.html.haml
.container
  .page-header
    %h1 
      Restaurant Categories
      %small 
        \- Choose one
      - if logged_in?
        = link_to "Add a category", new_category_path, class: 'btn btn-success pull-right'
      
  .category-list
    %ul 
      - @categories.each do |category|
        %li
          = link_to category do 
            %h3= category.name

app/views/categories/new.html.haml
.container 
  = render 'shared/errors', obj: @category 
  
  %h3 Create a new category
  .form.col-md-4
    = form_for @category do |f|
      .form-group 
        = f.label :name
        = f.text_field :name, class: 'form-control' 
      
      = f.submit class: 'btn btn-success'

app/views/categories/show.html.haml
.container
  .page-header
    %h1 
      = @category.name + " Restaurants"
  - @category.restaurants.each do |restaurant|
    .restaurant-card 
      = link_to restaurant do 
        %h3= restaurant.name
        = image_tag restaurant.image_url

app/views/layouts/_navigation.html.haml
%nav.navbar.navbar-default
  .container-fluid
    %ul.nav.navbar-nav
      - if logged_in?
        %li= link_to "Logout", logout_path, method: :delete, data: { confirm: "Are you sure?" }
      - else
        %li= link_to "Login", login_path
      %li= link_to "Restaurants", restaurants_path  
      %li= link_to "Categories", categories_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/restaurants/_form.html.haml
.form.col-md-4
  = form_for @restaurant do |f|
    .form-group
      = f.label :name
      = f.text_field :name, class: 'form-control'

    .form-group
      = f.label :description
      = f.text_area :description, class: 'form-control'

    .form-group
      = f.label :image, "Image File"
      = f.file_field :image

    .form-group
      = f.label :category
      = f.collection_select( :category_id, Category.all, :id, :name, {class: 'form-control'} )

    = f.submit class: "btn btn-success"

app/views/restaurants/edit.html.haml
.container 
  .message
    - if @restaurant.errors.any?
      .errors_display 
        - @restaurant.errors.full_messages.each do |msg|
          %li
            = msg 
  
  = render 'form'

app/views/restaurants/index.html.haml
.container
  .page-header
    %h1
      Restaurant Ratings!
      %small
        \- A place to share your reviews
      - if logged_in?
        = link_to "Add a restaurant", new_restaurant_path, class: 'btn btn-success pull-right'

  .restaurant-group
    - @restaurants.each do |restaurant|
      .restaurant-section
        = link_to restaurant do
          .well.well-sm
            %h5= restaurant.name
            = image_tag restaurant.image.url(:medium)

app/views/restaurants/new.html.haml
.container 
  = render 'shared/errors', obj: @restaurant
  
  = render 'form'

app/views/restaurants/show.html.haml
.container
  .errors
    = render 'shared/errors', obj: @review

  .row.section
    .page-header
      %h1
        = @restaurant.name
        - if logged_in?
          = link_to "Edit restaurant", edit_restaurant_path(@restaurant), class: 'btn btn-success pull-right'

    .restaurant
      = image_tag @restaurant.image.url(:large)
      %h4= @restaurant.description

  - if logged_in? && review_exists_already?(@restaurant, current_user)
    .row.section
      .review.well.col-md-8
        %h2 You've reviewed this location already! Hooray!

  - elsif logged_in?
    .row.section
      %h2 Write a Review for #{ @restaurant.name }
      .review-form.col-md-8
        = form_for [@restaurant, @review] do |f|
          .form-group
            = f.label :rating
            = f.select :rating, options_for_select(rating_options), {}, class: 'form-control'

          .form-group
            = f.label :content
            = f.text_area :content, class: 'form-control'

          = f.submit class: 'btn btn-success'

  - else
    .row.section
      .login-prompt
        %h2
          Login to write your review -
          = link_to "Login", login_path, class: 'btn btn-primary'
        %h5
          Not a User?
          = link_to "Sign up here!", new_user_path

  .row.section
    %h2 User Reviews
    .reviews-list
      - @restaurant.reviews.reload.each do |review|
        %hr
          .review-item.row.panel.panel-default
            %p
              Review by:
              = link_to review.user.username, user_path(review.user)
            %p Rating: #{review.rating.to_s}
            %p= review.content
            %p= clean_date_format(review)

app/views/shared/_errors.html.haml
.message
  - if obj.errors.any?
    .errors_display.alert.alert-danger
      %ul
      - obj.errors.full_messages.each do |msg|
        %li
          = msg 

app/views/shared/_messages.html.haml
.container
  .flash-messages 
    - if flash[:success] 
      .alert.alert-success
        = flash[:success] 
    - elsif flash[:danger]
      .alert.alert-danger
        = flash[:danger]

app/views/users/new.html.haml
.container
  = render 'shared/errors', obj: @user 
  
  %h3 Create your user account
  .new-user-form.col-md-4
    = form_for @user do |f|
      .form-group 
        = f.label :username
        = f.text_field :username, class: 'form-control'
        
      .form-group 
        = f.label :password
        = f.text_field :password, class: 'form-control'
      
      = f.submit class: 'btn btn-success'

app/views/users/show.html.haml
.container
  .page-header
    %h3 #{@user.username}'s Recent Reviews
    
  .review-list
    - @user.reviews.each do |review|
      .review-item.row.panel.panel-default
        %p= review.restaurant.name 
        %p
          Rating: 
          = review.rating 
        %p= review.content 
        %p= clean_date_format(review)
  
  